FROM debian                                                                                                   
                                                                                                      
ARG http_proxy                                                                                                  
ARG https_proxy                                                                                                 

RUN env                                                                                                                
RUN apt-get update                                                                                              
RUN apt-get install -y git-core python-virtualenv                                                               
RUN git clone https://github.com/chubin/qrenco.de                                                               
RUN cd qrenco.de && virtualenv ve/                                                                              
RUN cd qrenco.de && ve/bin/pip install -r requirements.txt 
RUN apt-get install -y qrencode

EXPOSE 8003

CMD cd qrenco.de && ve/bin/python bin/srv.py
